title: The Water's Edge
author: hobbes78
description: Musings about life, death, arts & technology
url: "https://hobbes78.github.io/"
google_analytics: G-JGH36S4YTE
disqus:
  shortname: the-waters-edge
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jemoji
