title: The Water's Edge
author: hobbes78
description: Musings about life, death, arts & technology
url: "https://hobbes78.github.io/"
disqus:
  shortname: the-waters-edge
theme: minima
plugins:
  - jemoji
